"""
This module provides a suite of functions for visualizing and analyzing the results
of a shot peening simulation or ML prediction. The tools include loading simulation data,
visualizing checkerboard patterns, computing deformed meshes, and visualizing deformation and stress
fields.

The primary workflow for a given simulation folder involves:
1. Loading simulation data from specified files.
2. Computing deformations based on nodal coordinates and displacements.
3. Visualizing checkerboard patterns, undeformed and deformed meshes, stress fields,
 and deformation magnitudes.

Functions:
---------
- load_data(file_path, description=""):
    Loads data from a numpy file and handles exceptions.

- visualize_checkerboard(simulation_folder):
    Visualizes the checkerboard pattern for expansion coefficients.

- compute_deformed_mesh(simulation_folder, scale_factor=1):
    Computes deformed mesh coordinates and element connectivity.

- visualize_mesh(node_coords, deformed_coords, element_nodes):
    Visualizes the undeformed and deformed mesh as line collections.

- visualize_stress_field(simulation_folder, deformed_coords, element_nodes):
    Visualizes the stress field on the deformed mesh using von Mises stress.

- visualize_deformation(simulation_folder, deformed_coords, element_nodes, aligned_displacements):
    Visualizes the deformation magnitude on the deformed mesh.

- main():
    Executes the entire workflow including loading data, computing deformations,
    and visualizing the results in steps.

Dependencies:
------------
- numpy: For handling numerical arrays and operations.
- matplotlib: For visualizing patterns, meshes, and stress fields.
- os: For handling file paths and directories.

Usage:
-----
This module is designed to work with specific data files generated by shot peening
simulations. Ensure the correct file paths and formats are provided. Run the script
directly to execute the main workflow.

Example:
-------
To use this module:
    1. Place the simulation data in the specified folder structure.
    2. Update the `simulation_folder` variable in the `main()` function.
    3. Run the script to generate visualizations for the checkerboard pattern,
       deformed meshes, stress fields, and deformation magnitudes.

"""

import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
import matplotlib.collections as mc


def load_data(file_path, description=""):
    """Load data from a numpy file and handle exceptions."""
    try:
        data = np.load(file_path)
        return data
    except Exception as e:  # pylint: disable=broad-except
        print(f"Error loading {description} data from {file_path}: {e}")
        return None


def visualize_checkerboard(simulation_folder):
    """Visualize the checkerboard pattern."""
    try:
        checkerboard_path = os.path.join(simulation_folder, "checkerboard.npy")
        checkerboard = load_data(checkerboard_path, "checkerboard")
        if checkerboard is None:
            return

        plt.figure(figsize=(6, 6))
        plt.imshow(checkerboard, cmap="viridis", origin="lower", extent=[0, 1, 0, 1])
        plt.colorbar(label="Expansion Coefficient")
        plt.title("Checkerboard Pattern of Expansion Coefficients")
        plt.xlabel("X Position (m)")
        plt.ylabel("Y Position (m)")
        plt.grid(False)
        plt.show()
    except Exception as e:  # pylint: disable=broad-except
        print(f"Error visualizing checkerboard: {e}")


def compute_deformed_mesh(simulation_folder, scale_factor=1):
    """Compute the deformed mesh coordinates."""
    try:
        node_coords = load_data(os.path.join(simulation_folder, "node_coords.npy"), "node coordinates")
        node_labels = load_data(os.path.join(simulation_folder, "node_labels.npy"), "node labels")
        displacements = load_data(os.path.join(simulation_folder, "displacements.npy"), "displacements")
        disp_node_labels = load_data(
            os.path.join(simulation_folder, "disp_node_labels.npy"), "displacement node labels"
        )

        if any(obj is None for obj in [node_coords, node_labels, displacements, disp_node_labels]):
            print("One or more required files are missing.")
            return None, None, None

        node_label_to_index = {label: idx for idx, label in enumerate(node_labels)}

        aligned_displacements = np.zeros_like(node_coords)
        for idx, label in enumerate(disp_node_labels):
            node_idx = node_label_to_index[label]
            aligned_displacements[node_idx] = displacements[idx]

        deformed_coords = node_coords + scale_factor * aligned_displacements

        element_connectivity = load_data(
            os.path.join(simulation_folder, "element_connectivity.npy"), "element connectivity"
        )
        if element_connectivity is None:
            print("Element connectivity file is missing.")
            return None, None, None

        element_nodes = [[node_label_to_index[label] for label in elem] for elem in element_connectivity]

        return node_coords, deformed_coords, element_nodes
    except Exception as e:  # pylint: disable=broad-except
        print(f"Error computing deformed mesh: {e}")
        return None, None, None


def visualize_mesh(node_coords, deformed_coords, element_nodes):
    """Visualize the undeformed and deformed mesh."""
    try:

        def create_mesh_lines(coords, elements):
            lines = []
            for elem in elements:
                element_coords = coords[elem]
                for i in range(len(element_coords)):
                    start = element_coords[i][:2]
                    end = element_coords[(i + 1) % len(element_coords)][:2]
                    lines.append([start, end])
            return lines

        undeformed_lines = create_mesh_lines(node_coords, element_nodes)
        deformed_lines = create_mesh_lines(deformed_coords, element_nodes)

        _, ax = plt.subplots(figsize=(10, 10))
        lc_undeformed = mc.LineCollection(undeformed_lines, colors="gray", linewidths=0.5)
        lc_deformed = mc.LineCollection(deformed_lines, colors="blue", linewidths=0.5)
        ax.add_collection(lc_undeformed)
        ax.add_collection(lc_deformed)
        ax.set_xlim([0, 1])
        ax.set_ylim([0, 1])
        ax.set_aspect("equal")
        ax.set_title("Undeformed (gray) and Deformed (blue) Mesh")
        ax.set_xlabel("X Position (m)")
        ax.set_ylabel("Y Position (m)")
        plt.show()
    except Exception as e:  # pylint: disable=broad-except
        print(f"Error visualizing mesh: {e}")


def visualize_stress_field(simulation_folder, deformed_coords, element_nodes):
    """Visualize the stress field on the deformed mesh."""
    try:
        stresses = load_data(os.path.join(simulation_folder, "stresses.npy"), "stresses")
        stress_element_labels = load_data(
            os.path.join(simulation_folder, "stress_element_labels.npy"), "stress element labels"
        )
        if stresses is None or stress_element_labels is None:
            return

        s11, s22, s12 = stresses[:, 0], stresses[:, 1], stresses[:, 3]
        von_mises_stress = np.sqrt(s11**2 - s11 * s22 + s22**2 + 3 * s12**2)
        element_label_to_stress = dict(zip(stress_element_labels, von_mises_stress))

        element_polygons = []
        element_stress_values = []

        for elem_indices, elem_label in zip(element_nodes, stress_element_labels):
            coords = deformed_coords[elem_indices][:, :2]
            element_polygons.append(coords)
            element_stress_values.append(element_label_to_stress.get(elem_label, 0))

        collection = PolyCollection(
            element_polygons, array=np.array(element_stress_values), cmap="jet", edgecolors="k", linewidths=0.5
        )
        _, ax = plt.subplots(figsize=(10, 10))
        ax.add_collection(collection)
        ax.autoscale_view()
        ax.set_aspect("equal")
        plt.colorbar(collection, ax=ax, label="Von Mises Stress (Pa)")
        ax.set_title("Stress Field on Deformed Mesh")
        ax.set_xlabel("X Position (m)")
        ax.set_ylabel("Y Position (m)")
        plt.show()
    except Exception as e:  # pylint: disable=broad-except
        print(f"Error visualizing stress field: {e}")


def visualize_deformation(_, deformed_coords, element_nodes, aligned_displacements):
    """Visualize the deformation magnitude on the deformed mesh."""
    try:
        deformation_magnitude = np.linalg.norm(aligned_displacements, axis=1)

        element_deformation_values = [deformation_magnitude[elem_indices].mean() for elem_indices in element_nodes]

        element_polygons = [deformed_coords[elem_indices][:, :2] for elem_indices in element_nodes]

        collection_def = PolyCollection(
            element_polygons, array=np.array(element_deformation_values), cmap="plasma", edgecolors="k", linewidths=0.5
        )

        _, ax = plt.subplots(figsize=(10, 10))
        ax.add_collection(collection_def)
        ax.autoscale_view()
        ax.set_aspect("equal")
        plt.colorbar(collection_def, ax=ax, label="Deformation Magnitude (m)")
        ax.set_title("Deformation Magnitude on Deformed Mesh")
        ax.set_xlabel("X Position (m)")
        ax.set_ylabel("Y Position (m)")
        plt.show()
    except Exception as e:  # pylint: disable=broad-except
        print(f"Error visualizing deformation: {e}")


def render_result_panels(folder_path: str, save_path: str) -> str:
    """Render a combined deformation + stress heat-map figure, save to save_path.

    Returns save_path so callers can display it.

    Panels (2 rows × 3 cols):
      Row 1: ux heat map | uz heat map | deformation magnitude
      Row 2: von Mises stress | S11 (radial/x residual) | S22 (hoop/y residual)

    Data sources (all node-level, from folder_path):
      node_coords.npy       (N, 3) -- grid positions
      displacements.npy     (N, 3) -- [ux, uy, uz] in metres
      nodal_stresses.npy    (N, 4) -- [S11, S22, S33, S12] in Pa (optional)

    - Use viridis for displacements, RdBu_r centred at 0 for signed components
    - Use plasma for stress magnitudes
    - All panels: units in µm for displacement, MPa for stress
    - Include colorbars with units
    - DPI=150, bbox_inches='tight'
    - If nodal_stresses.npy is missing, fill stress panels with a 'No stress data' text
    """
    node_coords = load_data(os.path.join(folder_path, "node_coords.npy"), "node_coords")
    displacements = load_data(os.path.join(folder_path, "displacements.npy"), "displacements")

    if node_coords is None or displacements is None:
        print(f"render_result_panels: required files missing in {folder_path}")
        return save_path

    try:
        nx = np.unique(np.round(node_coords[:, 0], 10))
        ny = np.unique(np.round(node_coords[:, 1], 10))
        H, W = len(nx), len(ny)

        ux_um = displacements[:, 0] * 1e6
        uz_um = displacements[:, 2] * 1e6
        mag_um = np.linalg.norm(displacements, axis=1) * 1e6

        def _grid(vals):
            try:
                return vals.reshape(H, W)
            except ValueError:
                return np.full((H, W), np.nan)

        nodal_stresses = load_data(os.path.join(folder_path, "nodal_stresses.npy"), "nodal_stresses")
        has_stress = nodal_stresses is not None and nodal_stresses.ndim == 2 and nodal_stresses.shape[1] >= 3

        fig, axes = plt.subplots(2, 3, figsize=(14, 8))

        # --- Row 1: displacement components ---
        vmax_ux = max(np.abs(ux_um).max(), 0.01)
        im0 = axes[0, 0].imshow(
            _grid(ux_um), origin="lower", aspect="equal", cmap="RdBu_r", vmin=-vmax_ux, vmax=vmax_ux
        )
        axes[0, 0].set_title("$u_x$ (in-plane)", fontsize=9)
        plt.colorbar(im0, ax=axes[0, 0], fraction=0.046, pad=0.04).set_label("µm", fontsize=8)

        vmax_uz = max(np.abs(uz_um).max(), 0.01)
        im1 = axes[0, 1].imshow(
            _grid(uz_um), origin="lower", aspect="equal", cmap="RdBu_r", vmin=-vmax_uz, vmax=vmax_uz
        )
        axes[0, 1].set_title("$u_z$ (out-of-plane)", fontsize=9)
        plt.colorbar(im1, ax=axes[0, 1], fraction=0.046, pad=0.04).set_label("µm", fontsize=8)

        im2 = axes[0, 2].imshow(_grid(mag_um), origin="lower", aspect="equal", cmap="viridis")
        axes[0, 2].set_title("Deformation magnitude", fontsize=9)
        plt.colorbar(im2, ax=axes[0, 2], fraction=0.046, pad=0.04).set_label("µm", fontsize=8)

        for ax in axes[0]:
            ax.set_xticks([])
            ax.set_yticks([])

        # --- Row 2: stress panels ---
        if has_stress:
            S11 = nodal_stresses[:, 0] * 1e-6  # Pa -> MPa
            S22 = nodal_stresses[:, 1] * 1e-6
            S12 = nodal_stresses[:, 3] * 1e-6 if nodal_stresses.shape[1] > 3 else np.zeros_like(S11)
            von_mises = np.sqrt(S11**2 - S11 * S22 + S22**2 + 3.0 * S12**2)

            im3 = axes[1, 0].imshow(_grid(von_mises), origin="lower", aspect="equal", cmap="plasma")
            axes[1, 0].set_title("von Mises stress", fontsize=9)
            plt.colorbar(im3, ax=axes[1, 0], fraction=0.046, pad=0.04).set_label("MPa", fontsize=8)

            vmax_s11 = max(np.abs(S11).max(), 0.01)
            im4 = axes[1, 1].imshow(
                _grid(S11), origin="lower", aspect="equal", cmap="RdBu_r", vmin=-vmax_s11, vmax=vmax_s11
            )
            axes[1, 1].set_title("S11 (radial residual)", fontsize=9)
            plt.colorbar(im4, ax=axes[1, 1], fraction=0.046, pad=0.04).set_label("MPa", fontsize=8)

            vmax_s22 = max(np.abs(S22).max(), 0.01)
            im5 = axes[1, 2].imshow(
                _grid(S22), origin="lower", aspect="equal", cmap="RdBu_r", vmin=-vmax_s22, vmax=vmax_s22
            )
            axes[1, 2].set_title("S22 (hoop residual)", fontsize=9)
            plt.colorbar(im5, ax=axes[1, 2], fraction=0.046, pad=0.04).set_label("MPa", fontsize=8)
        else:
            for ax in axes[1]:
                ax.set_facecolor("#f0f0f0")
                ax.text(
                    0.5,
                    0.5,
                    "No stress data",
                    ha="center",
                    va="center",
                    transform=ax.transAxes,
                    fontsize=11,
                    color="#888888",
                )
                ax.set_xticks([])
                ax.set_yticks([])

        for ax in axes[1]:
            ax.set_xticks([])
            ax.set_yticks([])

        fig.suptitle(f"Deformation & Stress — {os.path.basename(folder_path)}", fontsize=10)
        plt.tight_layout()
        fig.savefig(save_path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        print(f"render_result_panels: saved -> {save_path}")
    except Exception as e:  # pylint: disable=broad-except
        print(f"render_result_panels: error — {e}")

    return save_path


def visualize_all(folder_path, scale_factor):
    """
    This function runs through the whole visulization workflow
    Args:
        folder_path (String): The folder containing the files to visualize
        scale_factor (float): The factor to scale the deformation to visualize
    """
    print("Step 1: Visualizing Checkerboard Pattern...")
    visualize_checkerboard(folder_path)

    print("Step 2: Computing Deformed Mesh...")
    node_coords, deformed_coords, element_nodes = compute_deformed_mesh(folder_path, scale_factor)

    # Check if any of the required outputs are None
    if any(obj is None for obj in [node_coords, deformed_coords, element_nodes]):
        print("Error in computing deformed mesh. Exiting.")
        return

    print("Step 3: Visualizing Mesh (Undeformed and Deformed)...")
    visualize_mesh(node_coords, deformed_coords, element_nodes)

    print("Step 4: Visualizing Stress Field on Deformed Mesh...")
    visualize_stress_field(folder_path, deformed_coords, element_nodes)

    print("Step 5: Visualizing Deformation Magnitude on Deformed Mesh...")
    aligned_displacements = deformed_coords - node_coords
    visualize_deformation(folder_path, deformed_coords, element_nodes, aligned_displacements)

    print("Step 6: Rendering combined deformation + stress heat-map panels...")
    png_path = os.path.join(folder_path, "result_panels.png")
    render_result_panels(folder_path, png_path)


def main():
    """Main function to execute all visualization steps."""
    # Path to the simulation folder
    # simulation_folder = (r'\tests\simulation_0')
    simulation_folder = os.path.join(os.getcwd(), "tests", "simulation_0")

    # Deformation scale (adjust as needed)
    scale_factor = 1
    visualize_all(simulation_folder, scale_factor)


if __name__ == "__main__":
    main()


# ---------------------------------------------------------------------------
# 3D STL surface visualisation
# ---------------------------------------------------------------------------


def visualize_stl_deformation(stl_surface, displacements, colormap="plasma", scale_factor=1.0, show=True):
    """Render deformation magnitude on a 3D STL surface as a colour map.

    Parameters
    ----------
    stl_surface   : STLSurface instance (from stl_surface.py).
    displacements : (V, 3) float array of nodal displacements [ux, uy, uz].
    colormap      : matplotlib colormap name (default 'plasma').
    scale_factor  : Displacement exaggeration factor for visualisation.
    show          : Call plt.show() when True.

    Returns
    -------
    fig : matplotlib Figure
    """
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection

    vertices = stl_surface.vertices.astype(np.float64)
    disp = np.asarray(displacements, dtype=np.float64)
    deformed = vertices + scale_factor * disp
    magnitude = np.linalg.norm(disp, axis=1)

    # Per-face colour = mean magnitude of its 3 vertices
    face_mag = magnitude[stl_surface.faces].mean(axis=1)
    norm_mag = (face_mag - face_mag.min()) / ((face_mag.max() - face_mag.min()) + 1e-15)

    cmap = plt.get_cmap(colormap)
    face_color = cmap(norm_mag)

    tri_verts = deformed[stl_surface.faces]  # (F, 3, 3)
    poly = Poly3DCollection(tri_verts, facecolors=face_color, edgecolors="none", alpha=0.9)

    fig = plt.figure(figsize=(10, 7))
    ax = fig.add_subplot(111, projection="3d")
    ax.add_collection3d(poly)

    # Set axis limits to deformed bounding box
    for i, lbl in enumerate(["X", "Y", "Z"]):
        lo, hi = deformed[:, i].min(), deformed[:, i].max()
        pad = (hi - lo) * 0.05 + 1e-9
        getattr(ax, f"set_{lbl.lower()}lim")(lo - pad, hi + pad)
        getattr(ax, f"set_{lbl.lower()}label")(lbl)

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(face_mag.min(), face_mag.max()))
    sm.set_array([])
    fig.colorbar(sm, ax=ax, label="Displacement magnitude (m)", shrink=0.6)
    ax.set_title(f"STL Deformation  (scale × {scale_factor})")

    if show:
        plt.show()
    return fig


def visualize_stl_stress(stl_surface, stresses_per_face, colormap="jet", show=True):
    """Render von Mises stress on a 3D STL surface.

    Parameters
    ----------
    stl_surface      : STLSurface instance.
    stresses_per_face: (F, 4) float array [S11, S22, S33, S12] per triangle.
    colormap         : matplotlib colormap name (default 'jet').
    show             : Call plt.show() when True.

    Returns
    -------
    fig : matplotlib Figure
    """
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection

    s = np.asarray(stresses_per_face, dtype=np.float64)
    S11, S22, _, S12 = s[:, 0], s[:, 1], s[:, 2], s[:, 3]
    von_mises = np.sqrt(S11**2 - S11 * S22 + S22**2 + 3.0 * S12**2)

    norm_vm = (von_mises - von_mises.min()) / ((von_mises.max() - von_mises.min()) + 1e-15)
    cmap = plt.get_cmap(colormap)
    face_color = cmap(norm_vm)

    vertices = stl_surface.vertices.astype(np.float64)
    tri_verts = vertices[stl_surface.faces]
    poly = Poly3DCollection(tri_verts, facecolors=face_color, edgecolors="none", alpha=0.9)

    fig = plt.figure(figsize=(10, 7))
    ax = fig.add_subplot(111, projection="3d")
    ax.add_collection3d(poly)

    for i, lbl in enumerate(["X", "Y", "Z"]):
        lo, hi = vertices[:, i].min(), vertices[:, i].max()
        pad = (hi - lo) * 0.05 + 1e-9
        getattr(ax, f"set_{lbl.lower()}lim")(lo - pad, hi + pad)
        getattr(ax, f"set_{lbl.lower()}label")(lbl)

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(von_mises.min(), von_mises.max()))
    sm.set_array([])
    fig.colorbar(sm, ax=ax, label="von Mises stress (Pa)", shrink=0.6)
    ax.set_title("STL Residual Stress Field")

    if show:
        plt.show()
    return fig
